version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
      DB_HOST: db
    ports:
      - "5432:5432"
  app:
    image: productivity-frontend
    command: bundle exec rails s -p 3004 -b '0.0.0.0'
    volumes:
      - ".:/productivity"
    ports:
      - "3004:3004"
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env
